### ISSUE TITLE
Permissions to contribute to repository

### ISSUE THREAD

**Issue by cjackett** [kevinsbarnard/ifdo-py#1]
Hi Kevin,

Just looking to push a small commit to this repo so that iFDO tags are not automatically sorted when dumping to disk. If you could please modify the repo permissions I would be grateful :)

Kind regards,

-Chris

**Comment by kevinsbarnard** [comment]
Hi Chris!

Certainly; I just invited you as a collaborator.

Best,
Kevin

**Comment by cjackett** [comment]
Strange, I'm still getting this:

remote: Permission to kevinsbarnard/ifdo-py.git denied to cjackett.
fatal: unable to access 'https://github.com/kevinsbarnard/ifdo-py.git/': The requested URL returned error: 403

Could you please double-check the 'access level'?
https://stackoverflow.com/questions/52533318/how-to-solve-the-requested-url-returned-error-403-in-git-repository

**Comment by cjackett** [comment]
Ah, never-mind - I just needed to accept the invitation first.

**Comment by kevinsbarnard** [comment]
It looks like you need to accept the invite: https://github.com/kevinsbarnard/ifdo-py/invitations

**Comment by cjackett** [comment]
Okay, now trying to poetry publish v1.1.3 to PyPI - do I need permissions there too?

**Comment by kevinsbarnard** [comment]
Yes -- what's your PyPI username?

**Comment by cjackett** [comment]
cjackett

**Comment by kevinsbarnard** [comment]
Invite sent!
